import NavBar from "../components/Header/NavBar";
import React, {Component} from 'react';
import './About.css';

class About extends Component {
    render() {
      return (
        <div>
          <NavBar/>
            <div class="container">
              <div class="row">
                <div class="col-12 col-sm-6">
                  <div class="h1">About</div>
                  <div class="section-body2">
                    When designing a survey, careful consideration is made in wording questions and answer options. 
                    The goal is to yield responses that correctly represent what is being asked and reduce the chances of nonresponse.
                    Selecting a sample is equally as important. However, it is harder for students to get a sense of this in practice.
                    <br/>
                    <br/>
                    Our website provides a way for students to select from our preset questionnaires and build their own.
                    Then, they can decide what sampling method they will like to use, and we will build their own sample responses.
                    The final dataset will contain the answer responses to the selected questions for every "participant" in the form of a csv file.
                  </div>
                  <div class="h2">How it Works</div>
                  <div class="section-body2">
                    The responses are generated by providing weights to the possible answer choices.
                    These weights were determined by conducting a literature review of the distribution of these answers in a true population.
                    For example, census data was used to determine the distrubtion of genders.
                    INFO ON SAMPLING METHODS
                  </div>
                  <div class="h2">For Teachers</div>
                  <div class="section-body2">
                    Provide students an opportunity to have their own dataset using one of our sampling methods.
                    Students can perform the appropriate analysis on this data given their sampling method.
                    Every dataset will be different since they are randomly generated at the time of creation.
                  </div>
                </div>
              </div>
            </div>
        </div>
      );
    }
  }

  export default About;